## Data Preparation

In [49]:
# Import all required modules and packages

import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_info_columns', 500)
pd.set_option('display.max_rows', 500)

In [50]:
# Import the raw data containing all the items
raw_data = pd.read_csv('../data/1066/Base_1066_recodee_2017-06.txt', sep = '\s+', encoding='latin', na_values=999)

In [51]:
# check
raw_data.head(2)

,Id,Sexe,Age,Situfam,Enfant,Situpro,Typecontrat,Jourabsence,Revenus,Nivetude,Taillentrep,Manager,CSP1,CSP2,Secteur,CodePostal,ZoneFR1,ZoneFR2,MHCA1,MHCA2,MHCA3,MHCA4,MHCA5,MHCA6,MHCA7,MHCA8,MHCA9,MHCA10,MHCA11,MHCA12,MHCA13,MHCA14,MHCB1,MHCB2,MHCB3,MHCB4,MHCB5,MHCB6,MHCB7,MHCB8,MHCB9,MHCB10,MHCB11,MHCB12,MHCB13,MHCB14,MHCC1,MHCC2,MHCC3,MHCC4,MHCC5,MHCC6,MHCC7,MHCC8,MHCC9,MHCC10,MHCC11,MHCC12,MHCC13,MHCC14,PE1,PE2,PE3,PE4,PE5,PE6,PE7,PE8,PE9,PE10,PE11,PE12,PE13,PE14,PE15,PE16,PE17,PE18,PE19,PE20,Flux1,Flux2,Flux3,Flux4,Flux5,Flux6,Flux7,Flux8,Flux9,Flux10,Flux11,Flux12,Flux13,Cap1,Cap2,Cap3,AD1,AD2,AD3,AD4,AD5,AD6,AD7,AD8,AD9,AD10,EfP1,EfP2,EfP3,EfP4,EfP5,EfP6,EfP7,EfP8,UF1,UF2,UF3,UF4,UF5,UF6,HSE1,HSE2,HSE3,HSE4,HSE5,HSE6,HSE7,HSE8,HSE9,HSE10,HSE11,HSE12,HSE13,HSE14,HSE15,HSE16,HSE17,HSE18,HSE19,HSE20,HSE21,HSE22,HSE23,HSE24,HSE25,HSE26,HSE27,HSE28,HSE29,HSE30,HSE31,HSE32,HSE33,HSE34,HSE35,ALQ1,ALQ2,ALQ3,ALQ4,ALQ5,ALQ6,ALQ7,ALQ8,ALQ9,ALQ10,ALQ11,ALQ12,ALQ13,ALQ14,ALQ15,ALQ16,abs1,abs2,abs3,abs4,abs5,abs6,abs7,abs8,abs9,abs10,abs11,Imp1,Imp2,Imp3,Imp4,Imp5,Imp6,Force1,Force2,Force3,Force4,Force5,Force6,Force7,Force8,Force9,Force10,Force11,Force12,Force13,Force14,Force15,Force16,Force17,Force18,Force19,Force20,Force21,Force22,Force23,Force24,DÃ.marche,ExperDP,PratDP,cabs1,cabs2,cabs3,cabs4,cabs5,cabs6,cabs7
0,303,2,43,1,1,2,6,1.0,2,2,1,1,5,56,11,69008.0,5,8,6.0,5.0,5.0,NaN,1.0,NaN,NaN,NaN,5.0,5.0,5.0,6.0,6.0,6.0,6.0,5.0,5.0,1.0,1.0,1.0,5.0,NaN,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,4.0,NaN,NaN,4.0,1.0,1.0,NaN,6.0,5.0,2.0,6.0,NaN,6.0,5.0,5.0,5.0,NaN,NaN,5.0,2.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,5.0,NaN,5.0,1.0,NaN,4,7,4,5.0,5.0,6.0,5.0,6.0,5.0,4.0,5.0,6.0,5.0,5.0,5.0,6.0,5.0,5.0,5.0,6.0,5.0,5.0,5.0,6.0,6.0,NaN,5.0,5.0,5.0,3.0,5.0,3.0,3.0,NaN,4.0,3.0,4.0,5.0,3.0,NaN,5.0,5.0,3.0,NaN,5.0,3.0,2.0,5.0,NaN,4.0,NaN,5.0,NaN,5.0,3.0,4.0,5.0,3.0,3.0,4.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180,180,0,0,0,0,0,3.0,3.0,2.0,2.0,3.0,3.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,9.0,9.0,9.0,8.0,9.0,8.0,9.0,9.0,8.0,8.0,8.0,9.0,5.0,8.0,8.0,8.0,9.0,9.0,9.0,8.0,9.0,2,NaN,NaN,7,10,0,0,0,0,0
1,864,1,56,2,2,2,1,1.0,3,2,1,1,6,63,5,47240.0,4,7,1.0,2.0,1.0,4.0,1.0,1.0,4.0,4.0,2.0,2.0,2.0,3.0,3.0,2.0,1.0,2.0,2.0,3.0,1.0,1.0,3.0,3.0,2.0,1.0,3.0,2.0,2.0,2.0,3.0,2.0,1.0,4.0,1.0,1.0,4.0,3.0,3.0,3.0,4.0,4.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,5.0,6.0,1.0,6.0,1.0,1.0,6.0,2.0,2.0,5.0,2.0,1.0,1.0,5.0,3.0,5.0,6.0,4,3,4,4.0,2.0,1.0,3.0,3.0,1.0,1.0,3.0,1.0,1.0,3.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,1.0,1.0,5.0,4.0,3.0,4.0,1.0,4.0,1.0,1.0,2.0,1.0,4.0,2.0,4.0,2.0,3.0,4.0,4.0,3.0,1.0,3.0,4.0,5.0,1.0,1.0,1.0,2.0,1.0,1.0,4.0,1.0,1.0,4.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144,144,0,0,0,0,0,5.0,3.0,5.0,4.0,3.0,4.0,2.0,2.0,4.0,2.0,5.0,5.0,5.0,5.0,6.0,4.0,7.0,7.0,5.0,4.0,4.0,5.0,8.0,4.0,6.0,8.0,7.0,8.0,6.0,3.0,6.0,7.0,4.0,3.0,2,NaN,NaN,7,10,0,0,0,0,0

In [52]:
# replace variables to be consistent with previous research
raw_data.rename(columns={'Jourabsence':'GenAbs','cabs7':'ManAbs','cabs1':'PhysPres','cabs2':'PsycPres','abs8':'Turnover','abs10':'Unhappy'}, inplace=True)

In [53]:
# import the data with the factors scores, the probability and the FOP class
var_names = ['FOP','POSEM','NEGEM','FLOW','SELFDET','PERSEFF','STRENGTH','CPROB1','CPROB2','CPROB3','CPROB4','CL_FOP','ID']
clfop_data = pd.read_csv('../data/1066/Bi_ESEM_FOP_4cl_free.dat', sep='\s+', header = None, names=var_names )

In [54]:
# this to allow the possibility to compare quality of prediction with or wihout factor scores
'''
Set this variable True if you want to include the factor scores
'''
include_factor_scores = False

In [55]:
# define the columns of the factor score data with the raw data
if include_factor_scores:
  clfop_df = clfop_data.drop(columns=['CPROB1','CPROB2','CPROB3','CPROB4'])
else:
  clfop_df = clfop_data[['ID','CL_FOP']]

In [56]:
# now merge the raw data with factor score data
data = pd.merge(raw_data, clfop_df, left_on='Id',right_on='ID').drop(columns='ID')

In [57]:
# check the number of missing values
col_miss = data.isnull().sum()
col_miss

Id               0
Sexe             0
Age              0
Situfam          0
Enfant           0
Situpro          0
Typecontrat      0
GenAbs           1
Revenus          0
Nivetude         0
Taillentrep      0
Manager          0
CSP1             0
CSP2             0
Secteur          0
CodePostal       4
ZoneFR1          0
ZoneFR2          0
MHCA1           12
MHCA2            7
MHCA3           15
MHCA4           84
MHCA5           33
MHCA6           92
MHCA7           64
MHCA8           66
MHCA9           29
MHCA10          13
MHCA11          14
MHCA12          38
MHCA13          11
MHCA14          38
MHCB1           22
MHCB2           15
MHCB3           14
MHCB4           82
MHCB5           49
MHCB6          109
MHCB7           56
MHCB8           70
MHCB9           37
MHCB10          16
MHCB11          17
MHCB12          43
MHCB13          11
MHCB14          40
MHCC1            8
MHCC2            7
MHCC3           10
MHCC4          111
MHCC5           40
MHCC6          103
MHCC7           51
MHCC8           71
MHCC9           27
MHCC10          13
MHCC11          13
MHCC12          38
MHCC13          11
MHCC14          26
PE1             10
PE2              5
PE3             20
PE4             19
PE5             20
PE6             24
PE7             14
PE8             19
PE9             18
PE10            11
PE11            19
PE12            47
PE13             3
PE14             8
PE15             9
PE16            13
PE17            13
PE18            20
PE19             9
PE20            13
Flux1           28
Flux2           30
Flux3            5
Flux4           13
Flux5           14
Flux6           16
Flux7           24
Flux8           17
Flux9           16
Flux10          28
Flux11          43
Flux12          36
Flux13          23
Cap1             0
Cap2             0
Cap3             0
AD1              6
AD2              6
AD3             57
AD4             13
AD5              4
AD6             17
AD7              7
AD8              5
AD9             11
AD10            28
EfP1            12
EfP2            42
EfP3             8
EfP4             8
EfP5             7
EfP6             6
EfP7             8
EfP8             4
UF1              9
UF2              4
UF3             11
UF4             16
UF5             24
UF6             37
HSE1             4
HSE2             9
HSE3            10
HSE4             1
HSE5            14
HSE6            15
HSE7            21
HSE8             9
HSE9             4
HSE10           10
HSE11            2
HSE12            2
HSE13           11
HSE14           18
HSE15            1
HSE16           31
HSE17           26
HSE18            9
HSE19            4
HSE20            5
HSE21           10
HSE22          104
HSE23           47
HSE24           21
HSE25           11
HSE26          129
HSE27           14
HSE28           26
HSE29           47
HSE30            5
HSE31           25
HSE32           17
HSE33           34
HSE34            7
HSE35           59
ALQ1           755
ALQ2           757
ALQ3           757
ALQ4           756
ALQ5           755
ALQ6           757
ALQ7           760
ALQ8           777
ALQ9           778
ALQ10          772
ALQ11          756
ALQ12          756
ALQ13          763
ALQ14          783
ALQ15          766
ALQ16          767
abs1             0
abs2             0
abs3             0
abs4             0
abs5             0
abs6             0
abs7             0
Turnover         3
abs9            42
Unhappy          5
abs11            7
Imp1            30
Imp2            15
Imp3            13
Imp4             7
Imp5            12
Imp6            13
Force1          25
Force2          11
Force3          12
Force4          13
Force5          14
Force6          15
Force7          14
Force8          16
Force9          11
Force10         14
Force11         13
Force12         18
Force13         11
Force14         33
Force15         17
Force16         15
Force17         13
Force18         17
Force19         17
Force20         25
Force21          8
Force22         19
Force23         21
Force24         30
DÃ.marche        0
ExperDP        756
PratDP         756
PhysPres         0
PsycPres         0
cabs3            0
cabs4            0
cabs5            0
cabs6            0
ManAbs           0
CL_FOP           0
dtype: int64

In [58]:
# select for removal those variable that have more than 50% missing values
to_drop = data.columns[col_miss > 0.5*len(data)]

In [59]:
# drop those columns with more than 50% missing values
data = data.drop(columns = to_drop)

In [60]:
# check
data.isnull().sum()

Id               0
Sexe             0
Age              0
Situfam          0
Enfant           0
Situpro          0
Typecontrat      0
GenAbs           1
Revenus          0
Nivetude         0
Taillentrep      0
Manager          0
CSP1             0
CSP2             0
Secteur          0
CodePostal       4
ZoneFR1          0
ZoneFR2          0
MHCA1           12
MHCA2            7
MHCA3           15
MHCA4           84
MHCA5           33
MHCA6           92
MHCA7           64
MHCA8           66
MHCA9           29
MHCA10          13
MHCA11          14
MHCA12          38
MHCA13          11
MHCA14          38
MHCB1           22
MHCB2           15
MHCB3           14
MHCB4           82
MHCB5           49
MHCB6          109
MHCB7           56
MHCB8           70
MHCB9           37
MHCB10          16
MHCB11          17
MHCB12          43
MHCB13          11
MHCB14          40
MHCC1            8
MHCC2            7
MHCC3           10
MHCC4          111
MHCC5           40
MHCC6          103
MHCC7           51
MHCC8           71
MHCC9           27
MHCC10          13
MHCC11          13
MHCC12          38
MHCC13          11
MHCC14          26
PE1             10
PE2              5
PE3             20
PE4             19
PE5             20
PE6             24
PE7             14
PE8             19
PE9             18
PE10            11
PE11            19
PE12            47
PE13             3
PE14             8
PE15             9
PE16            13
PE17            13
PE18            20
PE19             9
PE20            13
Flux1           28
Flux2           30
Flux3            5
Flux4           13
Flux5           14
Flux6           16
Flux7           24
Flux8           17
Flux9           16
Flux10          28
Flux11          43
Flux12          36
Flux13          23
Cap1             0
Cap2             0
Cap3             0
AD1              6
AD2              6
AD3             57
AD4             13
AD5              4
AD6             17
AD7              7
AD8              5
AD9             11
AD10            28
EfP1            12
EfP2            42
EfP3             8
EfP4             8
EfP5             7
EfP6             6
EfP7             8
EfP8             4
UF1              9
UF2              4
UF3             11
UF4             16
UF5             24
UF6             37
HSE1             4
HSE2             9
HSE3            10
HSE4             1
HSE5            14
HSE6            15
HSE7            21
HSE8             9
HSE9             4
HSE10           10
HSE11            2
HSE12            2
HSE13           11
HSE14           18
HSE15            1
HSE16           31
HSE17           26
HSE18            9
HSE19            4
HSE20            5
HSE21           10
HSE22          104
HSE23           47
HSE24           21
HSE25           11
HSE26          129
HSE27           14
HSE28           26
HSE29           47
HSE30            5
HSE31           25
HSE32           17
HSE33           34
HSE34            7
HSE35           59
abs1             0
abs2             0
abs3             0
abs4             0
abs5             0
abs6             0
abs7             0
Turnover         3
abs9            42
Unhappy          5
abs11            7
Imp1            30
Imp2            15
Imp3            13
Imp4             7
Imp5            12
Imp6            13
Force1          25
Force2          11
Force3          12
Force4          13
Force5          14
Force6          15
Force7          14
Force8          16
Force9          11
Force10         14
Force11         13
Force12         18
Force13         11
Force14         33
Force15         17
Force16         15
Force17         13
Force18         17
Force19         17
Force20         25
Force21          8
Force22         19
Force23         21
Force24         30
DÃ.marche        0
PhysPres         0
PsycPres         0
cabs3            0
cabs4            0
cabs5            0
cabs6            0
ManAbs           0
CL_FOP           0
dtype: int64

## Recode Categorical Variables

In [61]:
# Recode the Demarche Column
data.rename(columns={'DÃ.marche':'Demarche'}, inplace=True)
data.columns[196]

'Demarche'

In [62]:
# recoding all categorical variables

data['Sexe'].replace({1:"Masculin",2:"Féminin"}, inplace=True)
data['Situfam'].replace({1:"Vit seul(e)", 2:"Vit en couple"}, inplace=True)
data['Situpro'].replace({1:"Indépendant", 2:"Salarié", 5:"En transition"}, inplace=True)
data['Revenus'].replace({1:'moins de 6000€', 2:'entre 6000€ et 11900€', 3:'entre 11901€ et 26490€', 4:'entre 26491€ et 70900€', 5:'entre 70901€ et 150000€', 6:'plus de 150001€'}, inplace=True)
data['Nivetude'].replace({1:'sans diplôme ou brevet de collège', 2: 'CAP/BEP', 3:'Baccalauréat', 4:'Bac+2 / +3', 5:'Bac+4 / Bac+5', 6:'Doctorat'}, inplace=True)
data['Taillentrep'].replace({1:"TPE (Moins de 10 salariés)",
                                 2:"Petite PME-PMI (Entre 10 et 49 salariés)",
                                 3:"Moyenne PME-PMI (Entre 50  et 199  salariés)",
                                 4:"Grande PME-PMI (Entre 200 et 499 salariés)",
                                 5:"Entreprise de Taille Intermédiaire (Entre 500 et 2000 salariés)",
                                 6:"Grands Groupes (Plus de 2000 salariés)"},inplace=True)
data['Manager'].replace({1:"Non", 2:"Manager intermédiaire ", 3:"Manager supérieur", 4:"Chef d'Entreprise"},inplace=True)
data['CSP1'].replace({1:"Agriculteurs",
                          2:"Artisans, commerçants et chefs d'entreprises",
                          3:"Cadres, professions intellectuelles supérieures et professions libérales",
                          4:"Professions intermédiaires",
                          5:"Employés",
                          6:"Ouvriers"},inplace=True)
data['CSP2'].replace({10:"Agriculteurs",
                          21:"Artisans",
                          22:"Commerçants et assimilés",
                          23:"Chefs d'entreprise de 10 salariés ou plus",
                          31:"Professions libérales",
                          33:"Cadres de la fonction publique",
                          34:"Professeurs, professions scientifiques",
                          35:"Professions de l'information, des arts et des spectacles",
                          37:"Cadres administratifs et commerciaux d'entreprises",
                          38:"Ingénieurs et cadres techniques d'entreprises",
                          42:"Professeurs des écoles, instituteurs et professions assimilées",
                          43:"Professions intermédiaires de la santé et du travail social",
                          44:"Clergé, religieux",
                          45:"Professions intermédiaires administratives de la fonction publique",
                          46:"Professions intermédiaires administratives et commerciales des entreprises",
                          47:"Techniciens (sauf techniciens tertiaires)",
                          48:"Contremaîtres, agents de maîtrise (maîtrise administrative exclue)",
                          52:"Employés civils et agents de service de la fonction publique",
                          53:"Agents de surveillance",
                          54:"Employés administratifs d'entreprise",
                          55:"Employés de commerce",
                          56:"Personnels des services directs aux particuliers",
                          62:"Ouvriers qualifiés de type industriel",
                          63:"Ouvriers qualifiés de type artisanal",
                          64:"Chauffeurs",
                          65:"Ouvriers qualifiés de la manutention, du magasinage et du transport",
                          67:"Ouvriers non qualifiés de type industriel",
                          68:"Ouvriers non qualifiés de type artisanal",
                          69:"Ouvriers agricoles et assimilés"}, inplace=True)
data['Secteur'].replace({1:"Industrie",
                             2:"Construction",
                             3:"Commerce et réparation",
                             4:"Transports et entreposages",
                             5:"Hébergement et restauration",
                             6:"Information et communication",
                             7:"Activités financières et d’assurance",
                             8:"Activités immobilières",
                             9:"Soutien aux entreprises",
                             10:"Enseignement, santé et action sociale",
                             11:"Services aux ménages",
                             12:"Autre"},inplace=True)
data['CL_FOP'].replace({
    1.0:"Full Optimal Functioning",
    2.0:"Moderate Anhedonic Functioning",
    3.0:"Amotivated Dysfunctioning",
    4.0:"Emotional(+) Optimal Functioning"
    }, inplace=True)
data['ZoneFR1'].replace({0:np.nan,1:'Ile de France',2:'Nord-Ouest',3:'Nord Est',4:'Sud-Ouest',5:'Sud Est'}, inplace=True)
data['ZoneFR2'].replace({0:np.nan,1:'Ile de France',2:'Banlieue Parisienne Ouest',3:'Ouest',4:'Nord',5:'Est',6:'Banlieue Parisienne Est',7:'Sud-Ouest',8:'Centre Est',9:'Méditerranée'},inplace=True)
data['Typecontrat'].replace({1:'Temps plein contrat 35h', 2:'Temps plein forfait', 3:'Mi-temps contrat 35h', 4:'Mi-temps forfait', 5:'Durée hébdomadaire', 6:'Je ne sais pas'} ,inplace=True)
data['Demarche'].replace({1:'Oui', 2:'Non'},inplace=True)

C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Sexe'].replace({1:"Masculin",2:"Féminin"}, inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Situfam'].replace({1:"Vit seul(e)", 2:"Vit en couple"}, inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Situpro'].replace({1:"Indépendant", 2:"Salarié", 5:"En transition"}, inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Revenus'].replace({1:'moins de 6000€', 2:'entre 6000€ et 11900€', 3:'entre 11901€ et 26490€', 4:'entre 26491€ et 70900€', 5:'entre 70901€ et 150000€', 6:'plus de 150001€'}, inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Nivetude'].replace({1:'sans diplôme ou brevet de collège', 2: 'CAP/BEP', 3:'Baccalauréat', 4:'Bac+2 / +3', 5:'Bac+4 / Bac+5', 6:'Doctorat'}, inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Taillentrep'].replace({1:"TPE (Moins de 10 salariés)",
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Manager'].replace({1:"Non", 2:"Manager intermédiaire ", 3:"Manager supérieur", 4:"Chef d'Entreprise"},inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['CSP1'].replace({1:"Agriculteurs",
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['CSP2'].replace({10:"Agriculteurs",
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:50: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Secteur'].replace({1:"Industrie",
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:62: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['CL_FOP'].replace({
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:68: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['ZoneFR1'].replace({0:np.nan,1:'Ile de France',2:'Nord-Ouest',3:'Nord Est',4:'Sud-Ouest',5:'Sud Est'}, inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:69: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['ZoneFR2'].replace({0:np.nan,1:'Ile de France',2:'Banlieue Parisienne Ouest',3:'Ouest',4:'Nord',5:'Est',6:'Banlieue Parisienne Est',7:'Sud-Ouest',8:'Centre Est',9:'Méditerranée'},inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:70: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Typecontrat'].replace({1:'Temps plein contrat 35h', 2:'Temps plein forfait', 3:'Mi-temps contrat 35h', 4:'Mi-temps forfait', 5:'Durée hébdomadaire', 6:'Je ne sais pas'} ,inplace=True)
C:\Users\Franck\AppData\Local\Temp\ipykernel_8964\428902476.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Demarche'].replace({1:'Oui', 2:'Non'},inplace=True)

In [63]:
# get ready for Machine Learning : remove the ID and Postal Code variables
df = data.drop(columns=['Id','CodePostal'])

In [64]:
# generate df_pos
df_pos = pd.DataFrame()
df_pos['PosEmAvg'] = df[['PE11','PE13','PE14','PE16','PE19']].mean(axis=1)
df_pos['NegEmAvg'] = df[['PE3','PE5','PE6','PE10','PE17']].mean(axis=1)

In [65]:
# Create positivity ratio column
df_pos['PosRatio'] = df_pos['PosEmAvg'] / df_pos['NegEmAvg']

In [66]:
# copy the CL_FOP column to df_pos
df_pos['CL_FOP'] = df['CL_FOP']

In [67]:
# group positiviy ratio by CL_FOP
df_pos_group = df_pos.groupby('CL_FOP').agg({'PosRatio': ['mean', 'std', 'count']}).reset_index()
df_pos_group

                             CL_FOP  PosRatio
                                         mean       std count
0         Amotivated Dysfunctioning  1.763677  1.042611   265
1  Emotional(+) Optimal Functioning  3.397816  1.094251   343
2          Full Optimal Functioning  4.038639  1.544753    29
3    Moderate Anhedonic Functioning  1.983675  0.947541   428